### PR TITLE
Changes in the documentation!

### PR DESCRIPTION
**Pull request by chaitanyak175**
Hi, I wasn't able to figure out the earlier issue you helped me with, but I updated the documents please can you review it as merge my pull request as this will be my first open-source contribution.

### CODE REVIEW

**Review by bschmalhofer — CHANGES_REQUESTED** [review]
The license blurb is standardized in all files. This text should not be changed without discussion. There is even a CodePolicy check that checks the license test. See https://github.com/RotherOSS/CodePolicy/blob/rel-11_0/Kernel/TidyAll/Plugin/OTOBO/Legal/LicenseValidator.pm.

Please revert that change.

**Review by bschmalhofer — CHANGES_REQUESTED** [review]
Please revert, as the license text is standardized.

**Review by bschmalhofer — CHANGES_REQUESTED** [review]
Please revert, as the license text is standardized.

**Review by bschmalhofer — CHANGES_REQUESTED** [review]
Please revert, as the license text is standardized.

**Comment by bschmalhofer** [comment]
Hi @chaitanyak175,

working on the code documentation is good idea. Unfortunately changing the license blurb is kind of tricky. These changes need to be discussed within the project and must be consistent across the whole project.

Please be not discouraged. Take another look at the documentation, I'm sure that you will find content and wordings that can be improved. I'm looking forward to your next patch.

Best regards.
   Bernhard

**Comment by chaitanyak175** [comment]
Yeah sure, I'll go through the documentation and try something different.

**Pull request closed without merging**
