### PR TITLE
Issue #1826: Added if-else-block for different age formatting for tic…

### PR DESCRIPTION
**Pull request by stefanhaerter**
…kets older than 24h

Closing #1826

### CODE REVIEW

**Review by svenoe — COMMENTED** [review]
Please check whether the change can be shifted to CustomerAge.
Also please merge into rel-11

**Comment by stefanhaerter** [comment]
As far as I understand sub CustomerAge, the implementation cannot be shifted because CustmerAge only has access to the age and not to the date.

**Comment by stefanhaerter** [comment]
After discussion, the decision is to add an optional parameter 'CreatedAt' to CustomerAge function as well as a sysconfig option and rendering the age as date if the parameter is present and the sysconfig option is set.

**Comment by stefanhaerter** [comment]
Closing this in favor of #2197

**Pull request closed without merging**
